name: DiffMethylTools
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - scipy=1.13.1
  - pandas=2.2.2
  - numpy=1.26.4
  - statsmodels=0.14.2
  - polars=1.6.0
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - rpy2=3.5.11
  - bioconductor-limma
  - pyarrow=11
  - ncurses=6.5
  - statsmodels=0.14.2
  - seaborn
  - minimap2=2.1.1
  - htslib=1.20
  - samtools=1.20
  - pyyaml
  - tqdm
  - pip
  - pip:
    - joblib

