site_name: DiffMethylTools Documentation
repo_url: https://github.com/qgenlab/DiffMethylTools
repo_name: qgenlab/DiffMethylTools

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - CLI Reference:
      - Analysis: analysis.md
      - Annotation: annotation.md
      - Plotting: plotting.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
